package pojo;
// Generated May 10, 2014 1:41:20 PM by Hibernate Tools 3.6.0



/**
 * ExistIn generated by hbm2java
 */
public class ExistIn  implements java.io.Serializable {


     private ExistInId id;
     private User user;
     private Circle circle;
     private String bolckStatue;
     private String deleteStatus;

    public ExistIn() {
    }

    public ExistIn( User user, Circle circle, String bolckStatue, String deleteStatus) {
       this.id = new ExistInId(user.getId(), circle.getId());
       this.user = user;
       this.circle = circle;
       this.bolckStatue = bolckStatue;
       this.deleteStatus = deleteStatus;
    }
    
    public ExistIn(ExistInId id, User user, Circle circle, String bolckStatue, String deleteStatus) {
       this.id = id;
       this.user = user;
       this.circle = circle;
       this.bolckStatue = bolckStatue;
       this.deleteStatus = deleteStatus;
    }
   
    public ExistInId getId() {
        return this.id;
    }
    
    public void setId(ExistInId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Circle getCircle() {
        return this.circle;
    }
    
    public void setCircle(Circle circle) {
        this.circle = circle;
    }
    public String getBolckStatue() {
        return this.bolckStatue;
    }
    
    public void setBolckStatue(String bolckStatue) {
        this.bolckStatue = bolckStatue;
    }
    public String getDeleteStatus() {
        return this.deleteStatus;
    }
    
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }




}


