package pojos;
// Generated Apr 19, 2014 3:45:32 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Circle generated by hbm2java
 */
public class Circle  implements java.io.Serializable {


     private Integer idCircle;
     private Users users;
     private String circleName;
     private Set existIns = new HashSet(0);

    public Circle() {
    }

	
    public Circle(Users users, String circleName) {
        this.users = users;
        this.circleName = circleName;
    }
    public Circle(Users users, String circleName, Set existIns) {
       this.users = users;
       this.circleName = circleName;
       this.existIns = existIns;
    }
   
    public Integer getIdCircle() {
        return this.idCircle;
    }
    
    public void setIdCircle(Integer idCircle) {
        this.idCircle = idCircle;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCircleName() {
        return this.circleName;
    }
    
    public void setCircleName(String circleName) {
        this.circleName = circleName;
    }
    public Set getExistIns() {
        return this.existIns;
    }
    
    public void setExistIns(Set existIns) {
        this.existIns = existIns;
    }




}


