package pojos;
// Generated Apr 12, 2014 12:23:51 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private CommentId id;
     private Event event;
     private User user;
     private Date commentDate;
     private String commentText;

    public Comment() {
    }

    public Comment(CommentId id, Event event, User user, Date commentDate, String commentText) {
       this.id = id;
       this.event = event;
       this.user = user;
       this.commentDate = commentDate;
       this.commentText = commentText;
    }
   
    public CommentId getId() {
        return this.id;
    }
    
    public void setId(CommentId id) {
        this.id = id;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getCommentDate() {
        return this.commentDate;
    }
    
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }
    public String getCommentText() {
        return this.commentText;
    }
    
    public void setCommentText(String commentText) {
        this.commentText = commentText;
    }




}


