package pojos;
// Generated Apr 12, 2014 12:23:51 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Location location;
     private String name;
     private int noOfSlots;
     private Date date;
     private String eventStatue;
     
     private Set notifications = new HashSet(0);
     private Set eventToLocations = new HashSet(0);
     private Set joinEvents = new HashSet(0);
     private Set comments = new HashSet(0);

    public Event() {
    }

	
    public Event(User user, Location location, String name, int noOfSlots, Date date, String eventStatue) {
        this.user = user;
        this.location = location;
        this.name = name;
        this.noOfSlots = noOfSlots;
        this.date = date;
        this.eventStatue = eventStatue;
    }
    public Event(User user, Location location, String name, int noOfSlots, Date date, String eventStatue, Set notifications, Set eventToLocations, Set joinEvents, Set comments) {
       this.user = user;
       this.location = location;
       this.name = name;
       this.noOfSlots = noOfSlots;
       this.date = date;
       this.eventStatue = eventStatue;
       this.notifications = notifications;
       this.eventToLocations = eventToLocations;
       this.joinEvents = joinEvents;
       this.comments = comments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getNoOfSlots() {
        return this.noOfSlots;
    }
    
    public void setNoOfSlots(int noOfSlots) {
        this.noOfSlots = noOfSlots;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getEventStatue() {
        return this.eventStatue;
    }
    
    public void setEventStatue(String eventStatue) {
        this.eventStatue = eventStatue;
    }
    public Set getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(Set notifications) {
        this.notifications = notifications;
    }
    public Set getEventToLocations() {
        return this.eventToLocations;
    }
    
    public void setEventToLocations(Set eventToLocations) {
        this.eventToLocations = eventToLocations;
    }
    public Set getJoinEvents() {
        return this.joinEvents;
    }
    
    public void setJoinEvents(Set joinEvents) {
        this.joinEvents = joinEvents;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


