package pojos;
// Generated Apr 19, 2014 3:45:32 PM by Hibernate Tools 3.2.1.GA



/**
 * EventToLocation generated by hbm2java
 */
public class EventToLocation  implements java.io.Serializable {


     private EventToLocationId id;
     private Location location;
     private Event event;
     private int toOrder;

    public EventToLocation() {
    }

    public EventToLocation(EventToLocationId id, Location location, Event event, int toOrder) {
       this.id = id;
       this.location = location;
       this.event = event;
       this.toOrder = toOrder;
    }
   
    public EventToLocationId getId() {
        return this.id;
    }
    
    public void setId(EventToLocationId id) {
        this.id = id;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public int getToOrder() {
        return this.toOrder;
    }
    
    public void setToOrder(int toOrder) {
        this.toOrder = toOrder;
    }




}


