package pojos;
// Generated Apr 19, 2014 3:45:32 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer idEvent;
     private Users users;
     private Location location;
     private String eventName;
     private int noOfSlots;
     private Date eventDate;
     private String eventStatue;
     private Set notifications = new HashSet(0);
     private Set eventToLocations = new HashSet(0);
     private Set joinEvents = new HashSet(0);
     private Set comments = new HashSet(0);

    public Event() {
    }

	
    public Event(Users users, Location location, String eventName, int noOfSlots, Date eventDate, String eventStatue) {
        this.users = users;
        this.location = location;
        this.eventName = eventName;
        this.noOfSlots = noOfSlots;
        this.eventDate = eventDate;
        this.eventStatue = eventStatue;
    }
    public Event(Users users, Location location, String eventName, int noOfSlots, Date eventDate, String eventStatue, Set notifications, Set eventToLocations, Set joinEvents, Set comments) {
       this.users = users;
       this.location = location;
       this.eventName = eventName;
       this.noOfSlots = noOfSlots;
       this.eventDate = eventDate;
       this.eventStatue = eventStatue;
       this.notifications = notifications;
       this.eventToLocations = eventToLocations;
       this.joinEvents = joinEvents;
       this.comments = comments;
    }
   
    public Integer getIdEvent() {
        return this.idEvent;
    }
    
    public void setIdEvent(Integer idEvent) {
        this.idEvent = idEvent;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public int getNoOfSlots() {
        return this.noOfSlots;
    }
    
    public void setNoOfSlots(int noOfSlots) {
        this.noOfSlots = noOfSlots;
    }
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }
    public String getEventStatue() {
        return this.eventStatue;
    }
    
    public void setEventStatue(String eventStatue) {
        this.eventStatue = eventStatue;
    }
    public Set getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(Set notifications) {
        this.notifications = notifications;
    }
    public Set getEventToLocations() {
        return this.eventToLocations;
    }
    
    public void setEventToLocations(Set eventToLocations) {
        this.eventToLocations = eventToLocations;
    }
    public Set getJoinEvents() {
        return this.joinEvents;
    }
    
    public void setJoinEvents(Set joinEvents) {
        this.joinEvents = joinEvents;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


