package pojos;
// Generated Apr 19, 2014 3:45:32 PM by Hibernate Tools 3.2.1.GA



/**
 * ExistInId generated by hbm2java
 */
public class ExistInId  implements java.io.Serializable {


     private int usersId;
     private int circleId;

    public ExistInId() {
    }

    public ExistInId(int usersId, int circleId) {
       this.usersId = usersId;
       this.circleId = circleId;
    }
   
    public int getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }
    public int getCircleId() {
        return this.circleId;
    }
    
    public void setCircleId(int circleId) {
        this.circleId = circleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExistInId) ) return false;
		 ExistInId castOther = ( ExistInId ) other; 
         
		 return (this.getUsersId()==castOther.getUsersId())
 && (this.getCircleId()==castOther.getCircleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsersId();
         result = 37 * result + this.getCircleId();
         return result;
   }   


}


