package pojos;
// Generated Apr 12, 2014 12:23:51 PM by Hibernate Tools 3.2.1.GA



/**
 * ExistIn generated by hbm2java
 */
public class ExistIn  implements java.io.Serializable {


     private ExistInId id;
     private User user;
     private Circle circle;
     private String bolckStatue;

    public ExistIn() {
    }

    public ExistIn(ExistInId id, User user, Circle circle, String bolckStatue) {
       this.id = id;
       this.user = user;
       this.circle = circle;
       this.bolckStatue = bolckStatue;
    }
   
    public ExistInId getId() {
        return this.id;
    }
    
    public void setId(ExistInId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Circle getCircle() {
        return this.circle;
    }
    
    public void setCircle(Circle circle) {
        this.circle = circle;
    }
    public String getBolckStatue() {
        return this.bolckStatue;
    }
    
    public void setBolckStatue(String bolckStatue) {
        this.bolckStatue = bolckStatue;
    }




}


