package pojos;
// Generated Apr 19, 2014 3:45:32 PM by Hibernate Tools 3.2.1.GA



/**
 * JoinEvent generated by hbm2java
 */
public class JoinEvent  implements java.io.Serializable {


     private JoinEventId id;
     private UserStatue userStatue;
     private Users users;
     private Event event;

    public JoinEvent() {
    }

    public JoinEvent(JoinEventId id, UserStatue userStatue, Users users, Event event) {
       this.id = id;
       this.userStatue = userStatue;
       this.users = users;
       this.event = event;
    }
   
    public JoinEventId getId() {
        return this.id;
    }
    
    public void setId(JoinEventId id) {
        this.id = id;
    }
    public UserStatue getUserStatue() {
        return this.userStatue;
    }
    
    public void setUserStatue(UserStatue userStatue) {
        this.userStatue = userStatue;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }




}


