package pojos;
// Generated Apr 12, 2014 12:23:51 PM by Hibernate Tools 3.2.1.GA



/**
 * JoinEvent generated by hbm2java
 */
public class JoinEvent  implements java.io.Serializable {


     private JoinEventId id;
     private Event event;
     private UserStatue userStatue;
     private User user;

    public JoinEvent() {
    }

    public JoinEvent(JoinEventId id, Event event, UserStatue userStatue, User user) {
       this.id = id;
       this.event = event;
       this.userStatue = userStatue;
       this.user = user;
    }
   
    public JoinEventId getId() {
        return this.id;
    }
    
    public void setId(JoinEventId id) {
        this.id = id;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public UserStatue getUserStatue() {
        return this.userStatue;
    }
    
    public void setUserStatue(UserStatue userStatue) {
        this.userStatue = userStatue;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


