package pojos;
// Generated Apr 19, 2014 3:45:32 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer idLocation;
     private String longitude;
     private String lattitude;
     private String altitude;
     private String address;
     private Set eventToLocations = new HashSet(0);
     private Set events = new HashSet(0);

    public Location() {
    }

	
    public Location(String longitude, String lattitude, String altitude, String address) {
        this.longitude = longitude;
        this.lattitude = lattitude;
        this.altitude = altitude;
        this.address = address;
    }
    public Location(String longitude, String lattitude, String altitude, String address, Set eventToLocations, Set events) {
       this.longitude = longitude;
       this.lattitude = lattitude;
       this.altitude = altitude;
       this.address = address;
       this.eventToLocations = eventToLocations;
       this.events = events;
    }
   
    public Integer getIdLocation() {
        return this.idLocation;
    }
    
    public void setIdLocation(Integer idLocation) {
        this.idLocation = idLocation;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getLattitude() {
        return this.lattitude;
    }
    
    public void setLattitude(String lattitude) {
        this.lattitude = lattitude;
    }
    public String getAltitude() {
        return this.altitude;
    }
    
    public void setAltitude(String altitude) {
        this.altitude = altitude;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getEventToLocations() {
        return this.eventToLocations;
    }
    
    public void setEventToLocations(Set eventToLocations) {
        this.eventToLocations = eventToLocations;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }




}


