package pojos;
// Generated Apr 12, 2014 12:23:51 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Notification generated by hbm2java
 */
public class Notification  implements java.io.Serializable {


     private NotificationId id;
     private Event event;
     private User user;
     private Date notificationDate;
     private String eventType;
     private String eventState;

    public Notification() {
    }

	
    public Notification(NotificationId id, Event event, User user, Date notificationDate) {
        this.id = id;
        this.event = event;
        this.user = user;
        this.notificationDate = notificationDate;
    }
    public Notification(NotificationId id, Event event, User user, Date notificationDate, String eventType, String eventState) {
       this.id = id;
       this.event = event;
       this.user = user;
       this.notificationDate = notificationDate;
       this.eventType = eventType;
       this.eventState = eventState;
    }
   
    public NotificationId getId() {
        return this.id;
    }
    
    public void setId(NotificationId id) {
        this.id = id;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getNotificationDate() {
        return this.notificationDate;
    }
    
    public void setNotificationDate(Date notificationDate) {
        this.notificationDate = notificationDate;
    }
    public String getEventType() {
        return this.eventType;
    }
    
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }
    public String getEventState() {
        return this.eventState;
    }
    
    public void setEventState(String eventState) {
        this.eventState = eventState;
    }




}


