package pojos;
// Generated Apr 19, 2014 3:45:32 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Notification generated by hbm2java
 */
public class Notification  implements java.io.Serializable {


     private NotificationId id;
     private Users users;
     private Event event;
     private Date notificationDate;
     private String eventType;
     private String eventState;

    public Notification() {
    }

	
    public Notification(NotificationId id, Users users, Event event, Date notificationDate) {
        this.id = id;
        this.users = users;
        this.event = event;
        this.notificationDate = notificationDate;
    }
    public Notification(NotificationId id, Users users, Event event, Date notificationDate, String eventType, String eventState) {
       this.id = id;
       this.users = users;
       this.event = event;
       this.notificationDate = notificationDate;
       this.eventType = eventType;
       this.eventState = eventState;
    }
   
    public NotificationId getId() {
        return this.id;
    }
    
    public void setId(NotificationId id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public Date getNotificationDate() {
        return this.notificationDate;
    }
    
    public void setNotificationDate(Date notificationDate) {
        this.notificationDate = notificationDate;
    }
    public String getEventType() {
        return this.eventType;
    }
    
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }
    public String getEventState() {
        return this.eventState;
    }
    
    public void setEventState(String eventState) {
        this.eventState = eventState;
    }




}


