package pojos;
// Generated Apr 19, 2014 3:45:32 PM by Hibernate Tools 3.2.1.GA



/**
 * Phone generated by hbm2java
 */
public class Phone  implements java.io.Serializable {


     private int idPhone;
     private Users users;

    public Phone() {
    }

    public Phone(int idPhone, Users users) {
       this.idPhone = idPhone;
       this.users = users;
    }
   
    public int getIdPhone() {
        return this.idPhone;
    }
    
    public void setIdPhone(int idPhone) {
        this.idPhone = idPhone;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


