package pojos;
// Generated Apr 12, 2014 12:23:51 PM by Hibernate Tools 3.2.1.GA



/**
 * Phone generated by hbm2java
 */
public class Phone  implements java.io.Serializable {


     private String phoneNumber;
     private User user;

    public Phone() {
    }

    public Phone(String phoneNumber, User user) {
       this.phoneNumber = phoneNumber;
       this.user = user;
    }
   
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


