/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package webservices;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author Mo5a
 */
@javax.ws.rs.ApplicationPath("home")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(webservices.AddCircle.class);
        resources.add(webservices.AddPhoneNo.class);
        resources.add(webservices.AddUserToCircle.class);
        resources.add(webservices.DeleteUserFromCircle.class);
        resources.add(webservices.EventManagement.class);
        resources.add(webservices.Register.class);
        resources.add(webservices.SearchEventByDriver.class);
        resources.add(webservices.SearchEventByFromLocation.class);
        resources.add(webservices.SearchEventByToLocation.class);
        resources.add(webservices.SendNotificationService.class);
        resources.add(webservices.UpdateCircle.class);
        resources.add(webservices.ViewUserNotification.class);
        resources.add(webservices.deleteCircle.class);
        resources.add(webservices.viewAllCircles.class);
        resources.add(webservices.viewCircleDetails.class);
        return resources;
    }
    
}
